### ISSUE TITLE
Inconsistent orientation when placing on ceiling.

### ISSUE THREAD

**Issue by kotoshii** [Luke100000/ImmersivePaintings#48] opened 2023-08-06 09:09 UTC
For example I have a vertical and wide pictures that look like this in my gallery:
![image](https://github.com/Luke100000/ImmersivePaintings/assets/40234487/37558914-3aeb-43a8-918a-81498ea9a520)

And when I'm placing the picture on the ceiling I expect the orientation to be the same as in gallery (like the one placed on the right). But when placed the picture appears to be upside down (on the left).

![image](https://github.com/Luke100000/ImmersivePaintings/assets/40234487/09effaa0-41c4-4bc0-acd7-f2578f9bd084)

This applies to both wide and vertical pictures. Also, the orientation is not consistent, meaning that when I placed e.g. vertical image looking on the north, then turned camera to other direction, placed e.g wide image, turned camera back to north and placed vertical image again, then its orientation is like of the wide image I placed before. For example, on a screenshot all the pictures were placed looking in the same direction, but before placing the very last one (vertical), I placed the wide image looking towards the wall (this one is not on the screenshot) and only then placed the last vertical image. As you can see, its orientation is different.
Feels like it remembers the orientation pattern or something like that.

Can you please explain how it actually works?

**Comment by Luke100000** [comment] 2023-08-06 14:09
Thanks, its caused by wrong math. Will be fixed next version. When fixed it will use your players yaw for orientation

**Comment by kotoshii** [comment] 2023-08-06 14:20
@Luke100000 Thanks for the answer!

**Closed as completed** 2023-08-06 15:00 UTC
Labels: bug
